(function(){var e=void 0,g=true,h=null,j=false;function k(){return function(){}}function l(a){return function(){return this[a]}}function m(a){return function(){return a}}var o,q=this;
function aa(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ba(a,b,c){return a.call.apply(a.bind,arguments)}function da(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}else return function(){return a.apply(b,arguments)}}
function s(a,b,c){s=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ba:da;return s.apply(h,arguments)}function ea(a,b){function c(){}c.prototype=b.prototype;a.ma=b.prototype;a.prototype=new c;a.prototype.constructor=a};var fa={scroll:5E3,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3},ga={scroll:2E4,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3};function ia(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function ja(a,b){var c="",d=ma(encodeURIComponent(a));d.splice(b||5,d.length);t(d,function(a){if(a==0)a="A";else{a>>>=0;for(var b="",d;a>0;)d=a%64,b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(d)+b,a>>>=6;a=b}c+=a});return c}
function ma(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,d=4023233417,f=2562383102,i=271733878,n=3285377520,r=[],p,C,M,P,S,ha=Math.ceil((a.length/4+2)/16),ca=[ha],N=0,E;N<ha;N++){ca[N]=[];for(p=0;p<16;p++)ca[N][p]=a.charCodeAt(N*64+p*4)<<24|a.charCodeAt(N*64+p*4+1)<<16|a.charCodeAt(N*64+p*4+2)<<8|a.charCodeAt(N*64+p*4+3)}N=(a.length-1)*8;a=ha-1;ca[a][14]=Math.floor(N/Math.pow(2,32));ca[a][15]=N&4294967295;for(N=0;N<ha;N++){for(E=0;E<16;E++)r[E]=
ca[N][E];for(E=16;E<80;E++)r[E]=(r[E-3]^r[E-8]^r[E-14]^r[E-16])<<1|(r[E-3]^r[E-8]^r[E-14]^r[E-16])>>>31;a=c;p=d;C=f;M=i;P=n;for(E=0;E<80;E++)S=Math.floor(E/20),S=(a<<5|a>>>27)+(S==0?p&C^~p&M:S==1?p^C^M:S==2?p&C^p&M^C&M:p^C^M)+P+b[S]+r[E]&4294967295,P=M,M=C,C=p<<30|p>>>2,p=a,a=S;c=c+a&4294967295;d=d+p&4294967295;f=f+C&4294967295;i=i+M&4294967295;n=n+P&4294967295}return[c,d,f,i,n]}
function na(a){var b=q.navigator,c=q.window.screen,d=[b.userAgent,b.platform,(new Date).getTimezoneOffset(),c.width+c.height+c.colorDepth];t(b.plugins,function(a){d.push(a.name+a.description+a.filename+a[0].type)});b=q.performance;d=d.concat([b&&b.now?b.now():"",document.title,q.location.href,u(),ia()]);return d.concat(a||[]).join()}function v(a,b,c){var d=Array.prototype.slice,f=d.call(arguments,2);return function(){return a.apply(b,f.concat(d.call(arguments)))}}
function w(a){return typeof a!=="undefined"}function oa(a){return a.replace(/^www\./,"")}function pa(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)}function qa(a,b,c){a.removeEventListener?a.removeEventListener(b,c,j):a.detachEvent&&a.detachEvent("on"+b,c)}function ra(a){return typeof a==="number"}function ta(a){return typeof a==="string"}function ua(a){return typeof a==="function"}
function va(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}function u(){return(new Date).getTime()}function wa(a){return encodeURIComponent(a)}function t(a,b){if((!!a&&a.constructor===Object)===g)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===j)break}else{c=0;for(var d=a.length;c<d;c++)if(b(a[c],c)===j)break}}function xa(a,b){for(var c=0,d=a.length;c<d;c++)if(b(a[c]))return c;return-1}function ya(a){var b=q.pSUPERFLY_video,a=xa(b,a);if(a>-1)return b[a]}
function za(a){return a===e?0:u()-a}function Aa(a,b){var c,d,f="c"+Math.round(Math.random()*1E9);d=250;a+=(a.indexOf("?")>-1?"&":"?")+(c||"callback")+"=_cb_call."+f;c=document.createElement("script");var i=Ba(f,c);c.id=f;c.type="text/javascript";c.charset="UTF-8";c.src=a;var n=document.getElementsByTagName("head");if(n=n&&n[0]){var r=q._cb_call||(q._cb_call={});d=setTimeout(Ca(b,i),d);r[f]=Da(b,i,d);n.appendChild(c)}}function Ca(a,b){return function(){b();a(e,"TIMEOUT")}}
function Da(a,b,c){return function(d){b(c);a(d)}}function Ba(a,b){return function(c){c&&clearTimeout(c);setTimeout(function(){b&&b.parentNode&&b.parentNode.removeChild(b)},0);var d=q._cb_call,f=j;if(d&&(c?delete d[a]:d[a]=Ea,t(d,function(){f=g;return j}),!f))try{delete q._cb_call}catch(i){q._cb_call=e}}}function Ea(){}
function Fa(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],d=0,f=b.length;d<=f;d++)c[d]=[d];for(var i=0,n=a.length;i<=n;i++)c[0][i]=i;for(var r,p,C,d=1;d<=f;d++)for(i=1;i<=n;i++)r=d-1,p=i-1,C=c[r][p],b.charAt(r)==a.charAt(p)?c[d][i]=C:(p=c[d][p]+1,r=c[r][i]+1,C+=2,c[d][i]=Math.min(p,r,C));return c[b.length][a.length]}function Ga(a){return a===e?0:u()-a}function x(a){return Math.round(a===-1||isNaN(a)?-1:a*1E3)}
var Ha,Ia=q.setInterval,y=q.clearInterval,Ja=q.setTimeout,Ka=q.clearTimeout;function La(a,b){return Ia(a,b)}function Ma(a){switch(a){case e:return"undefined";case "":return"empty";default:return a}}function Na(a){switch(a){case "undefined":break;case "empty":return"";default:return a}};function Oa(a,b){var c,b=b||"*";c=c||document;if("querySelectorAll"in c)return c.querySelectorAll(b+"["+a+"]");var d=[];c=c.getElementsByTagName(b);for(var f=c.length;f--;)c[f].getAttribute(a)&&d.push(c[f]);return d}function Pa(a,b,c){c=c||"";if(a===e)a=j;else{var d;if(!(d=c===""&&a.getAttribute(b)))if(d=a.getAttribute(b))d=a.getAttribute(b)===c;a=d?a:a===document.body?j:Pa(a.parentNode,b,c)}return a}
function Qa(a){var b,c;b="pageYOffset";c="scrollTop";if(a&&(a=Oa("data-cb-scroll-element"))&&a.length)return a[0][c];if(ra(q[b]))return q[b];else if(document.body&&document.body[c])return document.body[c];else if(document.documentElement[c])return document.documentElement[c];return 0}function Ra(){var a=document,a=a[a.compatMode==="CSS1Compat"?"documentElement":"body"].clientHeight||0;window.innerHeight&&(a=Math.min(window.innerHeight,a));return a}
function Sa(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}function Ta(a,b,c){a.ownerDocument||(a=a.correspondingUseElement);if(!a||!a.ownerDocument)return h;var d=a.ownerDocument.documentElement,f=0,i=w(c)?c+1:-1;ta(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==d&&f!==i;){if(c(a))return a;a=a.parentNode;f++}return h}
function Ua(a){return a.nodeName&&a.nodeName.toLowerCase()==="a"&&(!a.namespaceURI||a.namespaceURI==="http://www.w3.org/1999/xhtml")}function Va(a){a=a||window.event;return!a?h:Ta(a.target||a.srcElement,Ua,10)}function Wa(a,b){var c=document.createElement(a);t(b,function(a,b){c.setAttribute(b,a)});return c};function Xa(){this.oa={};this.Va=1}function z(a,b,c,d){a.Va++;a.oa[b]=a.oa[b]||{};a.oa[b][a.Va]=[c,d];return a.Va}function Ya(a,b){if(ta(b))a.oa[b]=e,delete a.oa[b];else if(ra(b)){var c=g;t(a.oa,function(a){t(a,function(f,i){if(parseInt(i,10)===b)return a[i]=e,delete a[i],c=j});return c})}}Xa.prototype.ya=function(a,b){if(this.oa[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];t(this.oa[a],function(a){var b;a&&a.length===2&&(b=a[0],a=a[1],b.apply(a,c))})}};
Xa.prototype.addEventListener=function(a,b){var c=z(this,a,b);b._cbEventId=c};Xa.prototype.removeEventListener=function(a,b){this.oa[a]&&this.oa[a][b._cbEventId]&&this.oa[a][b._cbEventId][0]===b&&Ya(this,b._cbEventId)};var A=new Xa;var B={};
B.H=function(){B.Nb?B.rb("pageload"):(B.Pc=[{target:q,event:"scroll"},{target:document.body,event:"keydown"},{target:document.body,event:"mousemove"},{target:q,event:"resize"},{target:document.body,event:"mousedown"}],B.xb=h,B.Ja=h,B.Mb={},B.Lb={},B.wc={},B.zb={},t(B.Pc,function(a){var b=a.event;pa(a.target,b,function(a){B.rb.call(B,b,a)})}),z(A,"f",function(){B.rb("focus")}),B.rb("pageload"),pa(document.body,"click",function(a){(a=Va(a))&&A.ya("c",a)},g),pa(document.body,"contextmenu",function(a){(a=Va(a))&&
A.ya("r",a)}),B.Nb=g)};B.Wc=function(){var a,b=B.wc.keydown;if(b===e)return j;b=u()-b;return b<=(a||15E3)&&b>=0};B.Za=function(a,b){var c=B.zb[a];if(!c)return"";var b=b||u(),d,f=0;t(c,function(a){d=Math.floor((b-a)/1E3);d>=0&&d<16&&(f|=1<<d)});c=("0000"+f.toString(16)).slice(-4);return c=="0000"?"":c};B.Vd=function(){B.zb={}};B.lc=100;
B.rb=function(a,b){if(!b)b=window.event;if(b&&a==="keydown"){var c=b.keyCode?b.keyCode:b.which;if(c===32||c>36&&c<41)a="scroll"}B.$d(a);if(B.xb===h)B.Jc(a);else if(!B.Ja||fa[B.Ja]<fa[a]||ga[B.Ja]<ga[a])B.Ja=a};B.$d=function(a){var b=u();B.wc[a]=b;var c=B.zb[a];c?c.length<2?c.push(b):c[c.length-2]>b-1E3?c[c.length-1]=b:c.push(b):c=[b];c.length>32&&c.shift();B.zb[a]=c};
B.Jc=function(a){B.xb=Ja(B.bd,B.lc);A.ya("a");B.Mb[a]!==h&&Ka(B.Mb[a]);B.Lb[a]!==h&&Ka(B.Lb[a]);B.Ic(a,B.Mb,fa,"i");B.Ic(a,B.Lb,ga,"j")};B.Ic=function(a,b,c,d){b[a]=Ja(function(){Ka(b[a]);delete b[a];var c=j;t(b,function(){c=g;return j});c||A.ya(d)},c[a]+B.lc)};B.bd=function(){Ka(B.xb);B.xb=h;if(B.Ja)B.Jc(B.Ja),B.Ja=h};var Za,$a,ab,bb,cb;(function(){var a,b;t(["","moz","o","ms","webkit"],function(c){a=(c+"Hidden").charAt(0).toLowerCase()+(c+"Hidden").slice(1);if(typeof q.document[a]==="boolean")return b=c,j});b!==e&&(bb=a,cb=(b+"VisibilityState").charAt(0).toLowerCase()+(b+"VisibilityState").slice(1),ab=b+"visibilitychange")})();var db=j;function eb(){db=cb&&q.document[cb]==="prerender"?g:j}function fb(){$a=g;A.ya("f")}function gb(){$a=j;A.ya("b")}
function hb(a,b,c){q.addEventListener?q.addEventListener(a,c,j):q.document.attachEvent&&q.document.attachEvent(b,c)}function ib(){var a=g;q.document.hasFocus&&(a=q.document.hasFocus());var b=j;bb&&(b=q.document[bb]);return a&&!b}function jb(){ib()?fb():gb()}function kb(a){eb();if(db){var b=j,c=function(){b||(eb(),db||(b=g,a(),q.window.setTimeout(function(){q.document.removeEventListener(ab,c,j)},100)))};q.document.addEventListener(ab,c,j)}else a()};function lb(){this.k=q._sf_async_config||{};this.qc=v(this.Cc,this)}lb.prototype.H=function(){this.Ec=0};lb.prototype.Cc=k();lb.prototype.fb=function(a){if(!db){var b=this.qc,c;c=new Image(1,1);if(b)c.onerror=b;c.src=a}};lb.prototype.xa=function(){this.qc=h};function mb(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace("+"," "),t(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b}function nb(a,b){var c="",d=q.location.href.split("?");if(d.length){var d=mb(d[1]),f=b||a;d[f]&&(c=d[f])}return c}function ob(a,b){return!b?g:a==="http:"&&b==="80"||a==="https:"&&b==="443"}
function pb(a){var b=[];t(qb,function(c){var d=a[c];w(d)&&(Object.prototype.toString.call(d)==="[object Array]"?t(d,function(a){b.push(c+"="+a)}):d&&d.constructor===Object?t(d,function(a,c){b.push(c+"="+a)}):((d+"").length||c=="r")&&b.push(c+"="+d))});b.push("_");return b.join("&")}
function rb(a){var b={hostname:"",pathname:"",search:"",protocol:"",port:"",hash:""};if(!a)return b;var c=document.createElement("a"),d=q.location;if(!/^https?:/.test(a)&&a.indexOf("javascript:")!==0)if(a.indexOf("//")===0)a=d.protocol+a;else if(a.indexOf("/")===0)var f=ob(d.protocol,d.port)?"":d.port,a=d.protocol+"//"+d.hostname+(f?":"+f:"")+a;else{var f=document.baseURI||d.href,i=f.indexOf("?");i===-1&&(i=f.indexOf("#"));if(i===-1)i=f.length;i=f.lastIndexOf("/",i);a=i===-1?"/"+a:f.substr(0,i)+"/"+
a}c.href=a;b.hostname=c.hostname;b.pathname=c.pathname;b.search=c.search;b.protocol=c.protocol;b.port=c.port;b.hash=c.hash;if(b.pathname.charAt(0)!=="/")b.pathname="/"+b.pathname;if(b.hostname==="")b.hostname=d.hostname;if(b.protocol==="")b.protocol=d.protocol;if(b.protocol==="javascript:")b.pathname="",b.hostname="",b.port="",b.hash="";if(ob(b.protocol,b.port)||b.port==="0")b.port="";return b}
function sb(a){var b=a.protocol;a.hostname&&(b+="//"+a.hostname,a.port&&(b+=":"+a.port));return b+a.pathname+a.search+a.hash};function D(a,b,c){a[b]=a[b]||c}function tb(a,b){for(var c=q[a]||[];c.length;)b(c.shift());q[a]={push:b}}function ub(a){t(document.getElementsByTagName("script"),function(b){if(b.src.match(/chartbeat.js/))return b=mb(b.src.split("?")[1]),D(a,"uid",b.uid),D(a,"domain",b.domain),j})}function vb(a,b){return a[b]?encodeURIComponent(a[b]):""}function wb(a){var b={};t(a,function(a,d){d.charAt(0)=="_"&&(b[d]=a)});return b};var F={};F.Zc=function(){try{F.create("_cb_test","1",1);var a=F.F("_cb_test");F.remove("_cb_test");return a==="1"}catch(b){return j}};F.F=function(a){a+="=";var b="";t(document.cookie.split(";"),function(c){for(;c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return b=c.substring(a.length,c.length),j});return b};
F.create=function(a,b,c){var d=q._sf_async_config;if(d&&d.noCookies)return"";d=new Date;d.setTime(u()+c*1E3);a=a+"="+b+("; expires="+d.toGMTString())+"; path=/";return document.cookie=a};F.remove=function(a){return F.F(a)?F.create(a,"",-86400):""};var G={};G.Z=function(a){var b=q._sf_async_config;if(!a&&b&&b.noCookies)return h;if(G.Z.Fb!==e)return G.Z.Fb;var a=u()+"",c,d;try{if((d=q.localStorage).setItem(a,a),c=d.getItem(a)===a,d.removeItem(a),c)return G.Z.Fb=d}catch(f){}return G.Z.Fb=h};G.F=function(a){var b=G.Z();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&u()>c)?(G.remove(a),""):b.getItem(a)||""};
G.create=function(a,b,c){var d=G.Z();if(d){var f=new Date;f.setTime(u()+c*1E3);try{d.setItem(a,b),d.setItem(a+"_expires",f.getTime())}catch(i){}}};G.remove=function(a){var b=G.Z();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function xb(a){this.tb=a||"";this.cd=G.Z()!==h||F.Zc();this.dc=j;yb(this)}o=xb.prototype;o.isSupported=l("cd");
function yb(a){if(!F.F("_cb_ls")){var b=G.Z()!==h,c=F.F("_SUPERFLY_lockout");c&&t(["","_v_","_p_"],function(b){a.create(b+"_SUPERFLY_lockout",c,600,g)});var d=F.F("_chartbeat3");d&&(a.create("_v__chartbeat3",d,34128E3,g),F.remove("_chartbeat3"));b&&((b=F.F("_chartbeat2"))&&a.create("_chartbeat2",b,34128E3,g),(b=F.F("_chartbeat_uuniq"))&&a.create("_chartbeat_uuniq",b,34128E3,g),(b=F.F("_chartbeat5"))&&a.create("_chartbeat5",b,60,g));F.create("_cb_ls","1",34128E3)}}
function zb(a){var b=a.dc;a.dc=j;return b}o.create=function(a,b,c,d){a=d?a:this.tb+a;(G.Z()?G:F).create(a,b,c);G.Z()&&F.create(a,b,c)};o.update=function(a,b,c,d,f,i,n){a=d?a:this.tb+a;f=ta(f)?f:"::";d=(d=this.F(a,g))?d.split(f):[];if(n&&d.length){var r=n(b),p=xa(d,function(a){return n(a)===r});p!==-1&&d.splice(p,1)}d.push(b);for(ra(i)&&d.length>i&&d.splice(0,d.length-i);d.length>1&&d.join(f).length>4E3;)d.shift();this.create(a,d.join(f),c,g)};
o.F=function(a,b){var a=b?a:this.tb+a,c=(G.Z()?G:F).F(a);if(!c&&G.Z()&&(c=F.F(a))&&F.F("_cb_ls")){this.dc=g;var d;switch(a){case "_SUPERFLY_lockout":d=600;break;case "_chartbeat4":d=60;break;case "_cb_cp":d=60;break;case "_chartbeat3":d=34128E3;break;default:d=34128E3}G.create(a,c,d)}return c};o.remove=function(a,b){a=b?a:this.tb+a;(G.Z()?G:F).remove(a);G.Z()&&F.remove(a)};function Ab(a){var b=h;if(a&&(b=Bb()))return b;var c=q.location,b=Cb(c.pathname),a=c.search||"",a=a.replace(/PHPSESSID=[^&]+/,""),d=/&utm_[^=]+=[^&]+/ig;(c=d.exec(c.search))&&(a=a.replace(d,""));d=/\?utm_[^=]+=[^&]+(.*)/i;(c=d.exec(a))&&(a=a.replace(d,c[1]!=""?"?"+c[1]:""));return b+a}function Bb(){var a=h;t(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical")return b=rb(b.href),a=Cb(b.pathname)+b.search+b.hash,j});return a}
for(var Db={},Eb=0;Eb<81;Eb++)Db["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(Eb)]=g;function Fb(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return Db[c]?String.fromCharCode(c):"%"+b.toUpperCase()}function Cb(a){if(!ta(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,Fb);return a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent)};function H(a,b){var c=I();return w(b)&&!w(c[a])?b:c[a]}function I(){w(q._cb_shared)||(q._cb_shared={});return q._cb_shared};var J={Sc:{IDLE:0,Rc:1,Qc:2,Bb:3},Tc:{IDLE:0,Rc:1,Qc:2,Bb:3},pa:0,qa:0};J.H=function(){if(!J.Nb)z(A,"a",J.jd,J),z(A,"i",J.nd,J),z(A,"f",J.ld,J),z(A,"b",J.kd,J),z(A,"j",J.md,J),J.Nb=g};J.M=function(){return J.pa};J.hd=function(){return J.qa};J.jd=function(){J.pa===1?J.Ga(3):J.pa===0&&J.Ga(2);J.qa===1?J.Fa(3):J.qa===0&&J.Fa(2)};J.nd=function(){J.pa===3?J.Ga(1):J.pa===2&&J.Ga(0)};J.md=function(){J.qa===3?J.Fa(1):J.qa===2&&J.Fa(0)};J.ld=function(){(J.pa===0||J.pa===2)&&J.Ga(3);(J.qa===0||J.qa===2)&&J.Fa(3)};
J.kd=function(){J.pa===3?J.Ga(2):J.pa===1&&J.Ga(0);J.qa===3?J.Fa(2):J.qa===1&&J.Fa(0)};J.Ga=function(a){J.pa=a;A.ya("s",a)};J.Fa=function(a){J.qa=a;A.ya("x",a)};function Gb(a,b){this.Kb=a||e;this.Rb=b||e;this.Qa=this.va=0;this.vc=v(this.sd,this);this.cc=this.ra=h}o=Gb.prototype;o.H=function(){this.Qa=this.va=0;this.ra=h;this.cc=z(A,"s",this.ab,this);this.ab(J.M())};o.ab=function(a){y(this.ra);this.ra=h;if(a===J.Sc.Bb)this.ra=Ia(this.vc,1E3)};o.sd=function(){if(this.Kb===e||this.Kb())this.va++,this.Qa++,this.Rb&&this.Rb()};o.terminate=function(){y(this.ra);this.ra=h;Ya(A,this.cc)};o.xa=function(){this.terminate();this.Rb=this.Kb=e};function Hb(a,b){Gb.call(this,a,b)}ea(Hb,Gb);Hb.prototype.H=function(){this.Qa=this.va=0;this.ra=h;this.cc=z(A,"x",this.ab,this);this.ab(J.hd())};Hb.prototype.ab=function(a){y(this.ra);this.ra=h;if(a===J.Tc.Bb)this.ra=Ia(this.vc,1E3)};function K(){lb.call(this);this.Ma=[];this.G=new xb(this.Lc);this.G.remove("_SUPERFLY_nosample");this.na=new Gb;this.Ka=new Hb;this.Tb=v(this.cb,this);pa(q,"unload",this.Tb);kb(v(this.H,this))}ea(K,lb);o=K.prototype;o.$b=g;
o.H=function(){K.ma.H.call(this);this.nb=this.Ra=0;this.Ha=u();this.Ea=ja(Ib(this));this.Yb=g;this.pb=72E5;if(this.$b){var a=+this.k.sessionLength;if(!isNaN(a))this.pb=a*6E4}a=H("d");if(!a){var a=[],b=this.G.F("_chartbeat2",g);b.length>0&&(a=b.split("."));a.length>4&&(a=[]);var b=u(),c=b-+(a[1]||0),d=b-+(a[2]||0),c=a[0]&&c>18E5&&d<2592E6?0:1;I().n=c;var d="1",f=a&&+a[2],c=a&&a[3];if(a&&f&&c)if(d=Math.abs((va(b)-va(f))/864E5)){d=Math.min(d,16)-1;for(f="";d--;)f+=0;d=(c+f+"1").slice(-16)}else d=c;c=
d;a[0]||(a[0]=this.k.utoken||ja(Ib(this),3),a[1]=b);a[2]=b;a[3]=c;this.k.utoken=this.hb;this.G.create("_chartbeat2",a.join("."),34128E3,g);I().d=a}this.ie=a.join(".");var i;c=+a[1];d=+a[2];if((b=a[3])&&c&&d)i=(Math.min((Math.abs((va(d)-va(c))/864E5)||0)+1,16,b.length)-1).toString(16),i+=("0000"+parseInt(b,2).toString(16)).slice(-4);this.uc=i;this.Pb=H("n",1);this.hb=a[0];this.na.H();this.Ka.H();J.H();B.H();Za||($a=ib(),ab&&q.document.addEventListener&&q.document.addEventListener(ab,jb,j),hb("focus",
"onfocusin",fb),hb("blur","onfocusout",gb),$a&&fb(),Za=g);this.bb=0;this.Vc=z(A,"a",this.vd,this)};function Jb(a){if(!a.G.F("_SUPERFLY_lockout")&&!db)a.ud?a.vb():(a.ud=g,!q._sf_async_config&&!q._cbq?(a.sb=v(a.vb,a),pa(q,"load",a.sb)):a.vb())}o.vb=function(){var a=q._sf_startpt,b=q._sf_endpt;if(ra(a))this.eb=ra(b)?b-a:u()-a;B.H();this.Pa=La(v(this.ka,this),15E3);this.ka()};
o.ka=function(){var a=this.na.Qa,a=this.k.reading&&+this.k.reading||a>0;if(this.nb<this.Ra&&!a)this.nb++;else{var b;if(Ha===e)b=q.navigator.userAgent,Ha=b.indexOf("AppleWebKit")>0&&b.indexOf("FBIOS")>0;b=Ha;b&&!a?this.nb++:(a?this.Ra=0:this.Eb(),this.nb=0,this.Ma.push(0),this.Ma.length>18&&this.Ma.shift(),this.$b&&u()-this.Ha>=this.pb?this.terminate():this.Ua())}};
o.Cc=function(){this.Ma.push(1);var a=0;t(this.Ma,function(b){a+=b});a<3?(this.Yb=g,this.Eb()):(this.terminate(),this.G.create("_SUPERFLY_lockout","1",600))};o.cb=k();o.vd=function(){var a=Kb(this);this.bb=Math.max(this.bb,a)};function Kb(a){return Qa(!!a.k.scrollElement)}o.Eb=function(){var a=this.Ra;this.Ra=a=a?Math.min(a*2,16):1};o.lb=function(){this.cb();this.terminate()};o.Kc=function(){this.H();Jb(this)};
function Lb(a){if(a.k.virtualReferrer)return g;a=(document.referrer||"").indexOf("://"+q.location.hostname+"/");return a!=-1&&a<9}function Mb(a){a=a.k.virtualReferrer;if(!a&&(a=document.referrer||"")){var b=rb(a);if(b.protocol==="http:"||b.protocol==="https:")b.pathname=Cb(b.pathname),a=sb(b)}return encodeURIComponent(a)}function Nb(a){a=a.k.title.slice(0,100);return encodeURIComponent(a)}function Ib(a){a=[Mb(a),Sa("Width"),Sa("Height")];return na(a)}
function Ob(a){var b=[],c=a.G.F("_chartbeat4");c&&(t(c.split("::"),function(a){b.push(encodeURIComponent(a))}),a.G.remove("_chartbeat4"));return b}o.terminate=function(){this.na.terminate();this.Ka.terminate();Ya(A,this.Vc);this.sb!==e&&qa(q,"load",this.sb);y(this.Pa);I().d=e;I().n=e};o.xa=function(){this.terminate();qa(q,"unload",this.Tb);this.Tb=this.sb=this.G=this.Ma=this.k=h;this.na.xa();this.na=h;this.Ka.xa();this.Ka=h;K.ma.xa.call(this)};function Pb(a){for(var b=H("m")||[];b.length;)a(b.shift());a={push:a};I().m=a};function Qb(a){var b=a.offsetLeft,c=a.offsetTop,d=Rb(a);b+=d.x;c+=d.y;for(var f=j,d=a.offsetParent;a&&a!==e&&a!==document.body;){if(a===d)d=Rb(a),b+=a.offsetLeft+d.x,c+=a.offsetTop+d.y,d=a.offsetParent;if(Sb(a,["position"]).position==="fixed"){f=g;break}a=a.parentElement}f&&(b+=0,c+=0);return{x:b,y:c}}
function Sb(a,b){var c={},d,f;q.getComputedStyle?d=q.getComputedStyle(a,h):a.currentStyle?f="currentStyle":a.style&&(f="style");t(b,function(b){c[b]=d?d[b]||d.getPropertyValue(b):a[f][b]});return c}var Tb=/matrix(3d)?\((.*)\)/;function Rb(a){var b={x:0,y:0},a=Sb(a,["transform"]).transform;if(!ta(a))return b;var c=a.match(Tb);if(!c)return b;var a=c[2].split(", "),d;w(c[1])?(c=12,d=13):(c=4,d=5);b.x=parseInt(a[c],10);b.y=parseInt(a[d],10);return b};function Ub(){var a=q.location.href,a=a.replace(/-{2,}/g,"-"),a=rb(a);a.pathname=Cb(a.pathname);return a}
function Vb(a){var b=F.F("_chartbeat6");if(!b)return h;var b=b.split("::"),c,d;if(b.length===1)c=b[0].split(","),d=0;else{var f,i=Ub(),n=sb(i);t(b,function(a,b){var i=a.split(","),p=Fa(n,decodeURIComponent(i[0]));if(p===0)return c=i,d=b,j;if(f===e||p<f)f=p,c=i,d=b})}b.splice(d,1);a="_chartbeat6="+b.join("::")+Wb(a);document.cookie=a;var a=[],b=decodeURIComponent(c[0]),i=decodeURIComponent(c[1]),r=c[2];c.splice(0,3);for(var p=c.length/2,C=0;C<p;C++)a.push({fe:b,origin:i,Sa:r,ed:c[C*2],ae:c[C*2+1]});
return a}function Wb(a){var b="",c;if(!(a&&a.constructor===Object))return b;a.zc&&(c=new Date,c.setTime(c.getTime()+a.zc),b+="; expires="+c.toGMTString());a.domain&&(b+="; domain="+a.domain);a.path&&(b+="; path="+a.path);return b}function Xb(a){var b=a.topStorageDomain,a=a.domain,c=q.location.hostname;return b?b:Yb(c,a)?a:c.replace(/^www\./,"")}function Yb(a,b){if(a===b)return g;for(var c=b.split("."),d=a.split(".");c.length;){if(d.length===0)return j;if(c.pop()!==d.pop())return j}return g}
function Zb(a,b,c,d){this.gd=a;this.fd=b;this.be=c;this.Sa=d};function $b(a,b){for(var c=b||document.documentElement,d=[],f=h,i=a,n,r,p,C,M,P;i&&i!==c;){n=i.nodeName.toLowerCase();f=i;r=f.nodeName;if((i=i.parentNode)&&i!==document.documentElement){p=i.children;C=0;for(M=0,P=p.length;M<P;M++){if(f===p[M]){n+="["+(1+M-C)+"]";break}p[M].nodeName!==r&&C++}}d.unshift(n)}return d.join("/")};function ac(){this.Lc="_t_";K.call(this)}ea(ac,K);o=ac.prototype;
o.H=function(){ac.ma.H.call(this);ub(this.k);var a=q.location;D(this.k,"mabServer","mabping.chartbeat.net");D(this.k,"title",document.title);D(this.k,"domain",a.hostname);D(this.k,"path",Ab(!!this.k.useCanonical));this.ta=oa(a.hostname);this.k.domain=oa(this.k.domain);this.Zd=Xb(this.k);this.Ya=this.ob=j;this.rc=[];var b=this,a=Vb({domain:"."+this.Zd,zc:6E4,path:"/"});if(a!==h)this.ob=g,t(a,function(a){b.rc.push(new Zb(a.origin,a.ed,a.ae,a.Sa))});this.Ac=0;this.wb=h;Pb(v(this.rd,this))};
o.Ua=function(){var a=this.na.va,b=bc(this),c,d=this;this.ob&&t(this.rc,function(f){c=b+"&x="+f.fd+"&v="+f.be+"&ml="+f.Sa+"&xo="+f.gd+"&e="+a;d.fb(c)});!this.Ya&&this.wb&&cc(this,this.wb);this.Ya=g};o.vb=function(){var a=q._sf_startpt,b=q._sf_endpt;if(ra(a))this.eb=ra(b)?b-a:u()-a;B.H();if(this.ob)this.Pa=La(v(this.ka,this),500);this.ka()};o.ka=function(){var a,b;this.Ya?(a=this.na.va,b=this.Ac*15,a-b>=15&&(this.Ua(),this.Ac+=1),a>=45&&this.terminate()):this.Ua()};
function bc(a){var b=a.k;return(q.location.protocol||"http:")+"//"+b.mabServer+"/ping/mab?h="+encodeURIComponent(b.domain)+"&p="+encodeURIComponent(b.path)+"&d="+encodeURIComponent(a.ta)+"&u="+a.hb+"&c="+Math.round((u()-a.Ha)/600)/100}o.cb=k();o.Xd=function(a){var b=a.d,c=h;b!==h&&(c={ac:b.s,Sa:b.g,yc:b.m});a={status:a.s,data:c,code:a.c,message:a.m};this.Ya?cc(this,a):this.wb=a};
function cc(a,b){var c=bc(a),d=b.status,f=b.data;if(d=="s"&&f!==h){var i=v(a.fb,a);f.ac&&f.ac.constructor===Object&&t(f.ac,function(a,b){i(c+"&x="+b+"&v="+a+"&ml="+f.Sa+"&e=-1")});Object.prototype.toString.call(f.yc)==="[object Array]"&&t(f.yc,function(a){i(c+"&me=3&ml="+f.Sa+"&x="+a)})}else d=="e"&&a.fb(c+"&me="+b.code)}o.rd=function(a,b){for(var c=0,d=arguments.length;c<d;c++){var a=arguments[c],f=a.shift();f==="t"?this.Xd.apply(this,a):f==="v"&&this.Wd.apply(this,a)}};
o.lb=function(){I().m=[];w(this.hc)&&this.hc();ac.ma.lb.call(this)};o.Wd=function(a){this.hc=a};o.terminate=function(){this.hc=this.ge=e;this.wb=h;this.Ya=this.ob=e;ac.ma.terminate.call(this)};if(!q.pSUPERFLY_mab){var dc=new ac,ec={};ec.evps=v(dc.lb,dc);ec.svps=v(dc.Kc,dc);q.pSUPERFLY_mab=ec;Jb(dc)};var fc,gc,hc;
function ic(a){if(a.origin==="https://chartbeat.com"&&(a=String(a.data),a.indexOf("_cb_hud_version=")===0)){var b=a.substr(16);jc();if(b!=="NONE")b=b.indexOf("HUD2.")===0?b.substr(5):"OLD",a="https://static.chartbeat.com/js/inpage.js",b!=="OLD"&&(a="https://static2.chartbeat.com/frontend_ng/hud/hud-inpage/hud-inpage-"+b+".js"),b=w(e)?e:{},b.src=a,a=Wa("script",b),a.setAttribute("type","text/javascript"),b=document.head||document.getElementsByTagName("head")[0],w(e)?e.appendChild(a):b&&b.appendChild(a)}}
function jc(){Ka(gc);gc=e;qa(q,"message",ic);hc&&hc.parentNode&&hc.parentNode.removeChild(hc);hc=e};function kc(){var a=q._sf_async_config&&q._sf_async_config.domain;if(a&&!fc){fc=g;a="https://chartbeat.com/publishing/hud2/versioninfo/?host="+encodeURIComponent(a);pa(q,"message",ic);gc=Ja(jc,1E4);var b=w(e)?e:{};b.src=a;a=Wa("iframe",b);a.style.display="none";w(e)?e.appendChild(a):document.body&&document.body.appendChild(a);hc=a}}
function lc(a){if(/[\/.]chartbeat\.com$/.test(a.origin)){var b=G.Z(g),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),kc(),qa(q,"message",lc))}};function mc(){"postMessage"in window&&pa(q,"message",v(this.od,this));K.call(this);tb("_cbq",v(this.Hc,this))}ea(mc,K);
mc.prototype.H=function(){mc.ma.H.call(this);var a=this.hb;I().u=a;a=this.Ea;I().t=a;this.Db=h;ub(this.k);a=q.location;D(this.k,"pingServer","ping.chartbeat.net");D(this.k,"title",document.title);D(this.k,"domain",a.hostname);this.k.path=this.k.path?Cb(this.k.path):Ab(!!this.k.useCanonical);this.ta=oa(a.hostname);this.k.domain=oa(this.k.domain);this.Xc=z(A,"c",this.Ad,this);this.Yc=z(A,"r",this.Bd,this);this.Oa=h};mc.prototype.Uc=function(a){this.Db=a};
mc.prototype.cb=function(){this.G.update("_chartbeat4",["t="+this.Ea,"E="+this.na.va,"EE="+this.Ka.va,"x="+Kb(this),"c="+Math.round((u()-this.Ha)/600)/100,"y="+Sa("Height"),"w="+Ra()].join("&"),60,e,e,1)};var qb="h,p,u,d,g,g0,g1,g3,g4,n,nc,f,c,x,m,y,o,w,j,R,W,I,E,e,v,r,vp,K,l1,KK,PA,b,A,_c,_m,t,V,z,i,L,tz,l,,sn,C,eS,eM,eD,eK,eR,EE".split(",");o=mc.prototype;
o.Ua=function(a){this.Ec++;var b={};b.g=this.k.uid;b.g0=vb(this.k,"sections");b.g1=vb(this.k,"authors");b.g2=vb(this.k,"zone");b.g3=vb(this.k,"sponsorName");b.g4=vb(this.k,"type");!this.k.noCookies&&this.G.isSupported()?b.n=this.Pb:b.nc=1;b.c=Math.round((u()-this.Ha)/600)/100;b.E=this.na.va;b.EE=this.Ka.va;var c=Kb(this);this.bb=Math.max(this.bb,c);b.x=c;b.m=this.bb;b.y=Sa("Height");b.o=Sa("Width");b.w=Ra();b.b=this.eb?this.eb:"";if(this.uc)b.f=this.uc;b[""]=wb(this.k);b.t=this.Ea;b.V=78;b.tz=(new Date).getTimezoneOffset();
b.sn=this.Ec;c=this.na.Qa;b.h=encodeURIComponent(this.k.domain);b.p=encodeURIComponent(this.k.path);b.u=this.hb;b.d=encodeURIComponent(this.ta);b.j=Math.round((this.Ra+2)*15E3/1E3);b.R=0;b.W=0;b.I=0;var d=b.c*6E4+this.Ha;b.eD=B.Za("mousedown",d);b.eM=B.Za("mousemove",d);b.eK=B.Za("keydown",d);b.eR=B.Za("resize",d);b.eS=B.Za("scroll",d);B.Vd();B.Wc()?b.W=1:this.k.reading&&+this.k.reading||c>0||b.c<0.09?b.R=1:b.I=1;b.e=c;c=Lb(this);if(this.Yb){this.Yb=j;if(c)this.Oa=nc(this);b.i=Nb(this);d=this.k.hudTrackable;
d!==e&&(b.L=d?"1":"0");this.k.alias&&(b.PA=encodeURIComponent(this.k.alias))}if(c){if(this.Oa){if(b.v=encodeURIComponent(this.Oa.path),b.K=oc(this.Oa),this.Oa.Qb>1)b.l1=this.Oa.Qb}else b.v=Mb(this);this.k.virtualReferrer&&(b.vp=1)}else b.r=Mb(this);c=Ma(b.v);I().v=c;c=Ma(b.r);I().r=c;b.A=this.Db?this.Db:"";b._c=nb("utm_campaign",this.k.campaignTag);b._m=nb("utm_medium",this.k.mediumTag);b.z=Ob(this);b.C=this.k.mobileApp?1:"";b.KK=a?oc(a):"";b.l=zb(this.G)?1:"";this.na.Qa=0;this.fb((q.location.protocol||
"http:")+"//"+this.k.pingServer+"/ping?"+pb(b))};
o.od=function(a){var b=this.k;if(a.origin==="http://"+(b.playerdomain||this.ta)){var c=a.data;if(ta(c)&&c.indexOf("cbqpush::")===0)a=c.split("::"),a.length==3&&(a=a.slice(1),a[0].indexOf("_")===0&&this.Hc(a));else if(c=="cbdata?"){var c="&u="+H("u"),d="&t="+H("t"),f="&v="+H("v"),i="&r="+H("r"),b="domain="+encodeURIComponent(b.domain)+"&uid="+encodeURIComponent(b.uid)+"&path="+encodeURIComponent(b.path)+"&title="+Nb(this)+"&referrer="+Mb(this)+"&internal="+(Lb(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.ta)+
c+d+f+i+"&utoken="+this.hb;a.source.postMessage(b,"*")}}};o.Hc=function(a){a[0]==="_demo"&&this.k._demo?this.k._demo=this.k._demo+"%2C"+a[1]:this.k[a[0]]=a[1];this.Ra=0};function pc(a){a=a.replace(/-{2,}/g,"-");a=rb(a);a.pathname=Cb(a.pathname);return a}o.Ad=function(a){qc(this,a,"c")};o.Bd=function(a){qc(this,a,"r")};
function qc(a,b,c){if(a.$b&&u()-a.Ha>=a.pb)a.terminate();else{var d=b.href||"",d=pc(d);if(d.protocol.indexOf("http")===0){var f=d.hostname!==q.location.hostname,d=sb(d),i=Ta(b,function(a){return a.id}),n=$b(b,i),r;i?(n&&(n="/"+n),n="*[@id='"+i.id+"']"+n,r=$b(b)):r=n;i=ja(n);r=ja(r);b=Qb(b);c={left:b.x,top:b.y,path:a.k.path,href:d,kc:i,Cb:r,jc:n,bc:c,Qb:0};a.Ua(c);f||a.G.update("_chartbeat5",rc(c),60,j,e,5,function(a){a=a.split(",");return a[2]+","+a[3]})}}}
function oc(a){return[a.left,a.top,a.kc,encodeURIComponent(a.jc),a.bc,encodeURIComponent(a.href),a.Cb].join("::")}function rc(a){var b=encodeURIComponent(a.jc),b=b.replace(/-/g,"%2D");b.length>512&&(b="");return[a.left,a.top,encodeURIComponent(a.path),encodeURIComponent(a.href),a.kc,b,a.bc,a.Cb].join(",")}
function nc(a){var b=a.G.F("_chartbeat5");if(!b)return h;var c=b.split("::"),b=c.length,d,f;if(b===1)d=c[0].split(","),f=0;else{var i,n=pc(q.location.href),r=sb(n);t(c,function(a,b){var c=a.split(","),n=Fa(r,decodeURIComponent(c[3]));if(n===0)return d=c,f=b,j;if(i===e||n<i)i=n,d=c,f=b})}c.splice(f,1);a.G.create("_chartbeat5",c.join("::"),60);(a=d[5])?(a=a.replace(/%2D/g,"-"),a=decodeURIComponent(a)):a="";return{left:d[0],top:d[1],path:decodeURIComponent(d[2]),href:decodeURIComponent(d[3]),kc:d[4]||
"",jc:a,Cb:d.length>7?d[7]:"",bc:d.length>6?d[6]:"c",Qb:b}}o.terminate=function(){Ya(A,this.Xc);Ya(A,this.Yc);mc.ma.terminate.call(this)};var L="ct",O="s1";function Q(a){this.a=a;this.B=this.D=j;this.q=u();this.ia()}o=Q.prototype;o.ia=function(){this.a.currentTime()>0&&!this.a.paused&&!this.a.ended&&this.ga();this.a.on("play",v(this.ga,this));this.a.ready(v(this.la,this))};o.la=function(){this.fa=this.a.mediainfo;this.D=g};o.ga=function(){this.B=g};o.P=function(){return this.D&&this.N()!==""};
o.Ib=function(){var a;this.a.cb_configs&&this.a.cb_configs.domain?a=this.a.cb_configs.domain:!a&&q._sf_async_config&&q._sf_async_config.domain&&(a=q._sf_async_config.domain);return a};o.Jb=function(){var a;this.a.cb_configs&&this.a.cb_configs.uid?a=this.a.cb_configs.uid:!a&&q._sf_async_config&&q._sf_async_config.uid&&(a=q._sf_async_config.uid);return a};
o.N=function(){if(!this.fa)this.fa=this.a.mediainfo;return(this.fa&&this.fa.hasOwnProperty("name")?this.fa.name:this.a.el().getAttribute("title"))||""};o.O=function(){if(!this.fa)this.fa=this.a.mediainfo;return(this.fa&&this.fa.hasOwnProperty("id")?this.fa.id:this.a.el().attributes["data-video-id"]&&this.a.el().attributes["data-video-id"].value?this.a.el().attributes["data-video-id"].value:this.a.src())||""};o.X=function(){return L};o.Q=m("");o.da=function(){var a=this.a.duration();return x(a)};
o.M=function(){return!this.B?O:this.a.ended()?"s4":this.a.paused()?"s3":"s2"};o.Y=function(){var a=this.a.currentTime();return x(a)};o.U=m(-1);o.ca=function(){if(!this.fa)this.fa=this.a.mediainfo;return(this.fa&&this.fa.hasOwnProperty("thumbnail")?this.fa.thumbnail:this.a.poster())||""};o.$=k();o.T=k();o.ea=function(){return Ga(this.q)};
o.aa=function(){var a=[];this.a.cb_configs&&this.a.cb_configs.sections?a=this.a.cb_configs.sections.split(","):a.length==0&&q._sf_async_config&&q._sf_async_config.sections&&(a=q._sf_async_config.sections.split(","));if(a.length>0&&a[0]!=="")return a};o.S=function(){var a=[];this.a.cb_configs&&this.a.cb_configs.authors?a=this.a.cb_configs.authors.split(","):a.length==0&&q._sf_async_config&&q._sf_async_config.authors&&(a=q._sf_async_config.authors.split(","));if(a.length>0&&a[0]!=="")return a};
o.ba=m("BCN");Q.prototype.getStrategyName=Q.prototype.ba;Q.prototype.isReady=Q.prototype.P;Q.prototype.getHost=Q.prototype.Ib;Q.prototype.getUid=Q.prototype.Jb;Q.prototype.getTitle=Q.prototype.N;Q.prototype.getVideoPath=Q.prototype.O;Q.prototype.getContentType=Q.prototype.X;Q.prototype.getAdPosition=Q.prototype.Q;Q.prototype.getTotalDuration=Q.prototype.da;Q.prototype.getState=Q.prototype.M;Q.prototype.getCurrentPlayTime=Q.prototype.Y;Q.prototype.getBitrate=Q.prototype.U;
Q.prototype.getThumbnailPath=Q.prototype.ca;Q.prototype.getPlayerType=Q.prototype.$;Q.prototype.getAutoplayType=Q.prototype.T;Q.prototype.getViewStartTime=Q.prototype.ea;Q.prototype.getSections=Q.prototype.aa;Q.prototype.getAuthors=Q.prototype.S;Q.verify=function(a){return a.controlBar!==e};function R(a){this.Va=this.ta=e;this.D=j;this.Gc=this.oc=-1;this.wa=h;this.a=a;this.B=j;this.Ub=g;this.q=u();this.Vb="";for(var a=window.experienceJSON.data.configuredProperties.plugins.list.split(" "),b=a.length,c=0;c<b;c++){var d=a[c];if((d.indexOf("chartbeat")>=0||d.indexOf("localhost")>=0)&&d.indexOf(".js")>=0){this.Vb=d;break}}if(this.Vb)a=mb(this.Vb),this.ta=a.domain,this.Va=a.uid;a=window.brightcove;this.a=a.api.getExperience();b=this.a.getModule(a.api.modules.APIModules.EXPERIENCE);b.getReady()?
this.Dc():b.addEventListener(a.player.events.ExperienceEvent.TEMPLATE_READY,s(this.Dc,this))}o=R.prototype;
o.Dc=function(){var a=window.brightcove,b=this.a.getModule(a.api.modules.APIModules.VIDEO_PLAYER),c=this;b.getVideoDuration(function(a){c.oc=Math.round(a)});b.getCurrentVideo(function(a){c.wa=a});a=a.api.events.MediaEvent;b.addEventListener(a.PROGRESS,s(this.Kd,this));b.addEventListener(a.STOP,s(this.Md,this));b.addEventListener(a.COMPLETE,s(this.Cd,this));b.addEventListener(a.BEGIN,s(this.ga,this));this.D=g};o.Kd=function(a){this.Gc=a.position;this.Aa=this.Ub=j};o.Md=function(){this.Ub=g};
o.Cd=function(){this.Aa=g};o.ga=function(){this.Aa=j;if(!this.B)this.B=g};o.P=l("D");o.N=function(){var a="";this.wa&&(a=this.wa.displayName);return a};o.O=function(){var a="";this.wa&&(a="video@"+this.ta+"/"+this.wa.id);return a};o.X=function(){return L};o.Q=m("");o.da=l("oc");o.M=function(){return!this.B?O:this.Aa?"s4":this.Ub?"s3":"s2"};o.Y=function(){return x(this.Gc)};o.U=m(-1);o.ca=function(){var a="";this.wa&&(a=this.wa.thumbnailURL);return a};o.$=k();
o.ea=function(){return isNaN(this.q)?0:za(this.q)};o.S=k();o.aa=function(){var a;this.wa&&(a=this.wa.tags);return a};o.T=m("unkn");o.ba=m("BC");o.Ib=l("ta");o.Jb=l("Va");R.prototype.isReady=R.prototype.P;R.prototype.getTitle=R.prototype.N;R.prototype.getVideoPath=R.prototype.O;R.prototype.getContentType=R.prototype.X;R.prototype.getAdPosition=R.prototype.Q;R.prototype.getTotalDuration=R.prototype.da;R.prototype.getState=R.prototype.M;R.prototype.getCurrentPlayTime=R.prototype.Y;
R.prototype.getBitrate=R.prototype.U;R.prototype.getThumbnailPath=R.prototype.ca;R.prototype.getPlayerType=R.prototype.$;R.prototype.getViewStartTime=R.prototype.ea;R.prototype.getAuthors=R.prototype.S;R.prototype.getSections=R.prototype.aa;R.prototype.getAutoplayType=R.prototype.T;R.verify=function(a){return a===window.brightcove};R.prototype.getStrategyName=R.prototype.ba;R.prototype.getHost=R.prototype.Ib;R.prototype.getUid=R.prototype.Jb;function T(){this.a=window.flowplayer();this.B=this.D=j;this.q=u();this.za=this.Da=e;this.yb=this.gb="";this.Ob=e;this.ia()}var sc=/url\(['"]?([^'"\)]*)['"]?\)/;o=T.prototype;
o.sc=function(){if(this.a.conf&&(this.yb=this.a.conf.title?this.a.conf.title:"",this.gb=this.a.conf.poster?this.a.conf.poster:"",this.yb&&this.gb))return g;var a=this.O(),b=Oa("name","param"),c=e;t(b,function(b){if(b.attributes.name&&b.attributes.name.value==="flashvars"&&b.value.indexOf(a)!==-1)return c=b,j});c===e&&(b=Oa("src","video"),t(b,function(b){if(b.attributes.src.value&&a.indexOf(b.attributes.src.value)!=-1)return c=b,j}));b=Pa(c,"data-swf");if(b===j)return j;var d=b.style.background;if(d){if(d=
d.match(sc))this.gb=d[1]}else this.gb=b.attributes.poster&&b.attributes.poster.value;this.yb=b.title;if(this.Ob!==e)clearInterval(this.Ob),this.D=g;return g};o.ia=function(){this.a.ke?this.la():this.a.bind("ready",s(this.la,this));this.a.bind("resume",s(this.ga,this));this.a.je&&this.ga()};o.la=function(){this.sc()===j?this.Ob=setInterval(s(this.sc,this),1E3):this.D=g};o.ga=function(){if(!this.B)this.B=g};o.P=l("D");o.N=l("yb");o.O=function(){return this.a.video.url||this.a.video.src};o.X=function(){return L};
o.Q=m("");o.da=function(){return this.a.video.duration};o.M=function(){return!this.B?O:this.a.he?"s4":this.a.paused?"s3":"s2"};o.Y=function(){return x(this.a.video.time)};o.U=m(-1);o.ca=l("gb");o.$=k();o.T=k();o.ea=function(){return isNaN(this.q)?0:za(this.q)};o.aa=l("Da");o.S=l("za");o.ba=m("FP");T.prototype.getStrategyName=T.prototype.ba;T.prototype.isReady=T.prototype.P;T.prototype.getTitle=T.prototype.N;T.prototype.getVideoPath=T.prototype.O;T.prototype.getContentType=T.prototype.X;
T.prototype.getAdPosition=T.prototype.Q;T.prototype.getTotalDuration=T.prototype.da;T.prototype.getState=T.prototype.M;T.prototype.getCurrentPlayTime=T.prototype.Y;T.prototype.getBitrate=T.prototype.U;T.prototype.getThumbnailPath=T.prototype.ca;T.prototype.getPlayerType=T.prototype.$;T.prototype.getAutoplayType=T.prototype.T;T.prototype.getViewStartTime=T.prototype.ea;T.prototype.getSections=T.prototype.aa;T.prototype.getAuthors=T.prototype.S;T.verify=function(){return!!window.flowplayer};function U(a){this.a=a;this.Ab=this.B=this.D=j;this.q=u();this.za=this.Da=e;this.ia()}o=U.prototype;o.ia=function(){this.a.readyState>0&&this.la();this.a.currentTime>0&&!this.a.paused&&!this.a.ended&&this.ga();this.a.addEventListener("canplay",v(this.la,this));var a=v(this.ga,this);this.a.addEventListener("playing",a);this.a.addEventListener("webkitbeginfullscreen",a);this.a.addEventListener("webkitendfullscreen",v(this.Sd,this))};o.la=function(){this.D=g};o.ga=function(){this.B=g;this.Ab=j};
o.Sd=function(){this.Ab=g};o.P=l("D");o.N=function(){return this.a.attributes.title&&this.a.attributes.title.value||""};o.O=function(){return this.a.currentSrc||""};o.X=function(){return L};o.Q=m("");o.da=function(){return x(this.a.duration)};o.M=function(){return!this.B?O:this.a.ended||this.Ab&&this.a.currentTime==this.a.duration?"s4":this.a.paused||this.Ab?"s3":"s2"};o.Y=function(){return x(this.a.currentTime)};o.U=m(-1);o.ca=function(){return this.a.poster||""};o.$=k();
o.T=function(){return this.a.autoplay?"auto":"man"};o.ea=function(){return Ga(this.q)};o.aa=l("Da");o.S=l("za");o.ba=m("H5");U.prototype.getStrategyName=U.prototype.ba;U.prototype.isReady=U.prototype.P;U.prototype.getTitle=U.prototype.N;U.prototype.getVideoPath=U.prototype.O;U.prototype.getContentType=U.prototype.X;U.prototype.getAdPosition=U.prototype.Q;U.prototype.getTotalDuration=U.prototype.da;U.prototype.getState=U.prototype.M;U.prototype.getCurrentPlayTime=U.prototype.Y;
U.prototype.getBitrate=U.prototype.U;U.prototype.getThumbnailPath=U.prototype.ca;U.prototype.getPlayerType=U.prototype.$;U.prototype.getAutoplayType=U.prototype.T;U.prototype.getViewStartTime=U.prototype.ea;U.prototype.getSections=U.prototype.aa;U.prototype.getAuthors=U.prototype.S;U.verify=function(a){var b=a instanceof HTMLElement&&a.nodeName==="VIDEO",a=a.getAttribute&&a.getAttribute("data-account")!==h;return b&&!a};function V(a){this.a=a;this.B=this.Aa=this.D=j;this.q=u();this.ia()}o=V.prototype;o.ia=function(){this.a.onReady(s(this.la,this));this.a.onTime(s(this.Od,this));this.a.onComplete(s(this.Pd,this))};o.la=function(){this.D=g};o.Od=function(){this.Aa=j;if(!this.B)this.B=g};o.Pd=function(){this.Aa=g};o.P=function(){this.a.getState();return this.D||this.a.getState()!==e};o.N=function(){var a=tc(this);return!a?"":a.title};
function tc(a){if(a.a.getPlaylistIndex===e)return a.a.getPlaylistItem();var b=a.a.getPlaylist();if(!b)return h;var c=b.length,a=a.a.getPlaylistIndex();return c===0||c<=a?h:b[a]}o.O=function(){var a=tc(this);return!a?"":a.mediaid||a.file};o.X=function(){return L};o.Q=m("");o.da=function(){var a=this.a.getDuration();if(a>0)return Math.round(a*1E3)};o.M=function(){if(!this.B)return O;var a=this.a.getState();return this.Aa?"s4":a&&a.toUpperCase()==="PAUSED"?"s3":"s2"};
o.Y=function(){var a=this.a.getPosition();return x(a)};o.U=m(-1);o.ca=function(){var a=tc(this);return!a?"":a.image};o.$=k();o.ea=function(){return isNaN(this.q)?0:za(this.q)};o.S=k();o.aa=k();o.T=m("unkn");o.ba=m("JW");V.prototype.getStrategyName=V.prototype.ba;V.prototype.isReady=V.prototype.P;V.prototype.getTitle=V.prototype.N;V.prototype.getVideoPath=V.prototype.O;V.prototype.getContentType=V.prototype.X;V.prototype.getAdPosition=V.prototype.Q;V.prototype.getTotalDuration=V.prototype.da;
V.prototype.getState=V.prototype.M;V.prototype.getCurrentPlayTime=V.prototype.Y;V.prototype.getBitrate=V.prototype.U;V.prototype.getThumbnailPath=V.prototype.ca;V.prototype.getPlayerType=V.prototype.$;V.prototype.getViewStartTime=V.prototype.ea;V.prototype.getAuthors=V.prototype.S;V.prototype.getSections=V.prototype.aa;V.prototype.getAutoplayType=V.prototype.T;V.verify=function(a){return w(a.id)&&w(a.registerPlugin)};function W(a){this.a=a;this.Nc="";this.ja=O;this.Ba=L;this.sa="";this.q=u();this.ia()}o=W.prototype;o.ia=function(){this.a.kBind("playerStateChange.cb",s(this.Rd,this));this.a.kBind("playerUpdatePlayhead.cb",s(this.Jd,this));this.a.kBind("playerPlayEnd.cb",s(this.Qd,this));this.a.kBind("adStart.cb",s(this.xd,this));this.a.kBind("adEnd.cb",s(this.wd,this));this.a.kBind("switchingChangeComplete.cb",s(this.Nd,this))};
o.Rd=function(a){switch(a){case "playing":this.ja="s2";break;case "buffering":this.ja="s3";break;case "paused":this.ja="s3"}};o.Jd=function(){this.ja="s2";this.a.kUnbind("playerUpdatePlayhead.cb")};o.Qd=function(){this.ja="s4"};o.xd=function(a){this.Ba="ad";switch(a){case "pre":this.sa="a1";break;case "post":this.sa="a3";break;case "mid":this.sa="a2";break;case "main":this.sa="a5"}};o.wd=function(){this.Ba=L};o.Nd=function(a,b){this.$c=b};
o.P=function(){return this.a.evaluate("{mediaProxy.entry.name}")!=h};o.N=function(){return this.a.evaluate("{mediaProxy.entry.name}")};o.O=function(){if(!this.P())return this.Nc;var a=this.a.evaluate("{mediaProxy.entry.id}");return(this.Nc=a)||""};o.X=l("Ba");o.Q=l("sa");o.da=function(){var a=this.a.evaluate("{duration}");return x(a)};o.M=l("ja");o.Y=function(){var a=this.a.evaluate("{video.player.currentTime}");return x(a)};o.U=l("$c");
o.ca=function(){return this.a.evaluate("{mediaProxy.entry.thumbnailUrl}")||""};o.$=k();o.T=function(){var a=this.a.evaluate("{configProxy.flashvars.autoPlay}"),b=this.a.evaluate("{configProxy.flashvars.playlistAPI.autoContinue}"),c=this.a.evaluate("{playlistAPI.dataProvider.selectedIndex}");return b&&c>0?"cont":a?"auto":"man"};o.ea=function(){return isNaN(this.q)?0:Ga(this.q)};o.aa=function(){var a=this.a.evaluate("{mediaProxy.entry.tags}");if(a)return a.split(",")};
o.S=function(){var a=this.a.evaluate("{mediaProxy.entry.creatorId}");if(a)return[encodeURIComponent(a)]};o.ba=m("KT");W.prototype.getStrategyName=W.prototype.ba;W.prototype.isReady=W.prototype.P;W.prototype.getTitle=W.prototype.N;W.prototype.getVideoPath=W.prototype.O;W.prototype.getContentType=W.prototype.X;W.prototype.getAdPosition=W.prototype.Q;W.prototype.getTotalDuration=W.prototype.da;W.prototype.getState=W.prototype.M;W.prototype.getCurrentPlayTime=W.prototype.Y;W.prototype.getBitrate=W.prototype.U;
W.prototype.getThumbnailPath=W.prototype.ca;W.prototype.getPlayerType=W.prototype.$;W.prototype.getAutoplayType=W.prototype.T;W.prototype.getViewStartTime=W.prototype.ea;W.prototype.getSections=W.prototype.aa;W.prototype.getAuthors=W.prototype.S;W.verify=function(a){return typeof a.kBind=="function"};function X(a){this.mc=e;this.a=a;this.xc=e;this.D=j;this.La=e;this.B=j;this.za=this.Da=this.q=e;this.mc=q.OO;this.xc=this.a.mb;this.q=u();this.ia()}o=X.prototype;
o.ia=function(){var a=this.xc,b=this.mc.EVENTS;a.subscribe(b.CONTENT_TREE_FETCHED,"OoyalaStrategyPlugin",s(this.la,this));a.subscribe(b.WILL_PLAY_ADS,"OoyalaStrategyPlugin",s(this.zd,this));a.subscribe(b.PLAYING,"OoyalaStrategyPlugin",s(this.ga,this));a.subscribe(b.ADS_PLAYED,"OoyalaStrategyPlugin",s(this.yd,this));a.subscribe(b.METADATA_FETCHED,"OoyalaStrategyPlugin",s(this.Id,this));a.subscribe(b.EMBED_CODE_CHANGED,"OoyalaStrategyPlugin",s(this.Dd,this))};o.la=function(){this.D=g};
o.zd=function(){var a=this.a.getPlayheadTime(),b=this.a.getDuration();isNaN(a)&&(a=0);this.La=a===0?"a1":uc(a,b)?"a3":"a2"};o.ga=function(){this.B=g};o.yd=function(){this.La=e};o.Id=k();o.P=function(){var a=this.a.getState();if(a==="ready"||a==="playing"||a==="paused")this.D=g;return this.D};o.N=function(){var a=this.a.getItem();return a?a.title:""};o.O=function(){return(this.a.getItem()||{}).embedCode||this.a.embedCode||""};o.X=function(){return this.La===e?L:"ad"};
o.Q=function(){return this.La?this.La:""};o.da=function(){var a=this.a.getDuration();return a===-1||isNaN(a)?-1:a*1E3};o.M=function(){if(!this.B)return O;if(this.a.getState()==="paused")return"s3";var a=this.a.getPlayheadTime(),b=this.a.getDuration();return uc(a,b)?"s4":"s2"};function uc(a,b){return a===b||Math.floor(a)===Math.floor(b)||Math.ceil(a)===Math.ceil(b)||Math.ceil(a)===Math.floor(b)||Math.floor(a)===Math.ceil(b)}o.Dd=function(){this.La=e};
o.Y=function(){var a=this.a.getPlayheadTime();return a===-1||isNaN(a)?-1:a*1E3};o.U=function(){return this.a.getTargetBitrate()};o.ca=function(){var a=this.a.getItem();return!a?"":a.promo||a.promo_image||a.thumbnail_image};o.$=k();o.T=k();o.ea=function(){return isNaN(this.q)?0:Ga(this.q||0)};o.aa=l("Da");o.S=l("za");o.ba=m("OO");X.prototype.getStrategyName=X.prototype.ba;X.prototype.isReady=X.prototype.P;X.prototype.getTitle=X.prototype.N;X.prototype.getVideoPath=X.prototype.O;
X.prototype.getContentType=X.prototype.X;X.prototype.getAdPosition=X.prototype.Q;X.prototype.getTotalDuration=X.prototype.da;X.prototype.getState=X.prototype.M;X.prototype.getCurrentPlayTime=X.prototype.Y;X.prototype.getBitrate=X.prototype.U;X.prototype.getThumbnailPath=X.prototype.ca;X.prototype.getPlayerType=X.prototype.$;X.prototype.getAutoplayType=X.prototype.T;X.prototype.getViewStartTime=X.prototype.ea;X.prototype.getSections=X.prototype.aa;X.prototype.getAuthors=X.prototype.S;
X.verify=function(a){return a.hasOwnProperty("mb")&&a.hasOwnProperty("subscribe")&&a.hasOwnProperty("modules")&&a.hasOwnProperty("adPlaying")};function Y(a){this.a=a;this.ha=h;this.$a="";this.ja=O;this.Ba=L;this.sa="";this.q=u();this.a.controller.plugInLoaded&&this.a.controller.plugInLoaded(this)}o=Y.prototype;o.td=function(a){this.ia(a.controller)};
o.ia=function(a){a.addEventListener("OnLoadRelease",v(this.Bc,this));a.addEventListener("OnLoadReleaseUrl",v(this.Bc,this));a.addEventListener("OnReleaseStart",v(this.Ld,this));a.addEventListener("OnMediaPlay",v(this.Fd,this));a.addEventListener("OnMediaStart",v(this.Hd,this));a.addEventListener("OnMediaPause",v(this.Sb,this));a.addEventListener("OnMediaComplete",v(this.Ed,this));a.addEventListener("OnMediaError",v(this.Sb,this));a.addEventListener("OnMediaBuffer",v(this.Sb,this));a.addEventListener("OnMediaPlaying",
v(this.Gd,this))};o.Bc=function(a){if(a.data&&a.data.title)this.ha=a.data;if(a.data&&a.data.guid)this.$a=a.data.guid};o.Ld=function(a){t(a.data.clips,function(a){if(a=a.baseClip.guid)return this.$a=a,j});if(this.$a&&a.data.release&&a.data.release.title)this.ha=a.data.release};o.Fd=function(){this.ja="s2"};o.Hd=function(a){this.ja="s2";a=a.data.baseClip;a.isAd?(this.Ba="ad",this.sa=a.isMid?"a2":"a1"):(this.Ba=L,this.sa="")};o.Sb=function(){if(this.ja!=O)this.ja="s3"};o.Ed=function(){this.ja="s4"};
o.Gd=function(a){this.dd=a.currentTime};o.P=function(){return this.ha!=h};o.N=function(){return this.ha.title};o.O=function(){return!this.$a?"":this.$a};o.X=l("Ba");o.Q=l("sa");o.da=function(){return this.ha.duration};o.M=l("ja");o.Y=l("dd");o.U=function(){return this.ha.bitrate};o.ca=function(){return this.ha&&this.ha.defaultThumbnailUrl?this.ha.defaultThumbnailUrl:this.ha.pid?"http://link.theplatform.com/s/ngc/"+this.ha.pid+"?format=poster&height=70&width=95":""};o.$=k();o.T=k();
o.ea=function(){return isNaN(this.q)?0:this.q===e?0:u()-this.q};o.aa=function(){var a=this.ha.keywords?this.ha.keywords.split(","):[],b=[];t(this.ha.categories?this.ha.categories:[],function(a){b.push(encodeURIComponent(a.name))});t(a,function(a){b.push(encodeURIComponent(a.trim()))});return b};o.S=k();o.ba=m("TP");Y.prototype.initialize=Y.prototype.td;Y.prototype.getStrategyName=Y.prototype.ba;Y.prototype.isReady=Y.prototype.P;Y.prototype.getTitle=Y.prototype.N;Y.prototype.getVideoPath=Y.prototype.O;
Y.prototype.getContentType=Y.prototype.X;Y.prototype.getAdPosition=Y.prototype.Q;Y.prototype.getTotalDuration=Y.prototype.da;Y.prototype.getState=Y.prototype.M;Y.prototype.getCurrentPlayTime=Y.prototype.Y;Y.prototype.getBitrate=Y.prototype.U;Y.prototype.getThumbnailPath=Y.prototype.ca;Y.prototype.getPlayerType=Y.prototype.$;Y.prototype.getAutoplayType=Y.prototype.T;Y.prototype.getViewStartTime=Y.prototype.ea;Y.prototype.getSections=Y.prototype.aa;Y.prototype.getAuthors=Y.prototype.S;
Y.verify=function(a){return typeof a.controller!=="undefined"};function vc(a,b){this.a=a;this.Mc=b;this.Na=window.location!=window.parent.location;this.Fc=j;this.Yd=u();this.Lc="_v_";this.ua={};K.call(this)}ea(vc,K);var wc=q.QUICK_TEST?1E4:6E4,xc="autoDetect",yc={de:"title",ee:"videopath",ce:"thumbnailpath"},zc={};o=vc.prototype;
o.H=function(){this.Pb=(this.Ta=this.G.F("_chartbeat3"))?0:1;this.ic=this.Zb=g;this.Hb=j;this.ub=this.Wb=this.pc=this.Ia=e;this.Xa=15E3;this.ib=e;this.Td=this.ec=this.fc=this.jb=this.kb=0;var a=q.location;this.Xb=j;if(!this.Ta||this.Ta.length===0)this.Ta=ja(Ib(this),3);this.G.create("_chartbeat3",this.Ta,34128E3);var b;(b=this.Mc)&&ua(b)?(this.J=new b(this.a),b=g):b=j;if(b){D(this.k,"pingServer","ping.chartbeat.net");D(this.k,"title",document.title);D(this.k,"domain",a.hostname);D(this.k,"path",Ab(!!this.k.useCanonical));
this.J.getPlayerType&&D(this.k,"video_type",this.J.getPlayerType());this.pc=setInterval(v(this.ad,this),1E3);if(this.Na===g)this.qb=v(this.pd,this),pa(window,"message",this.qb),this.ib=setInterval(this.Ud,1E3);vc.ma.H.call(this)}};o.Eb=k();
o.ka=function(){if(this.J){if(!Ac(this))this.ic=g;if(!this.ic)return u()-this.Ha>=this.pb&&clearInterval(this.Ia),vc.ma.ka.call(this);if(this.J.isReady())this.Hb=this.ic=j,this.Wb=Bc(this),Cc(this),this.Ia=setInterval(v(this.Gb,this),100),vc.ma.ka.call(this);else if(!this.Hb){this.Hb=g;if(this.Td++>150)throw"Error: Video strategy never reported its ready state";clearInterval(this.Pa);this.Pa=setInterval(v(this.ka,this),100)}}};
o.Ua=function(){if(this.J){var a=this.k,b=this.J,c=b.getState(),d=Ac(this),f=this.Na?[]:q._cbq||(q._cbq=[]),i=b.getViewStartTime(),n=Dc(this),r=b.getAutoplayType?b.getAutoplayType():e,i=i===-1?-1:i/1E3,n=n?encodeURIComponent(n):e;if(!zc.path||zc.path===d||c==="s2"&&zc.state!=="s2")switch(zc={path:d,state:c},f.push(["_vi",wa(Ec(this))]),f.push(["_vp",d]),f.push(["_vdd",encodeURIComponent("video@"+(a.videodomain||a.domain))]),f.push(["_vs",b.getState()]),b.getContentType&&f.push(["_vt",b.getContentType()]),
b.getAdPosition&&f.push(["_vap",b.getAdPosition()]),f.push(["_vtn",wa(Dc(this))]),f.push(["_vd",b.getTotalDuration()]),b.getState()){case O:case "s2":case "s3":f.push(["R","1"]);break;case "s4":f.push(["R","0"])}a=Fc(this)+Z("_vt",b.getContentType?b.getContentType():"")+Z("_vap",b.getAdPosition?b.getAdPosition():"")+Z("_vs",c)+Z("_vbr",b.getBitrate?b.getBitrate():"")+Z("_vvs",i)+Z("_vpt",b.getCurrentPlayTime())+Z("_vtn",n)+Z("_vaup",r||"unkn")+Z("_vplt",a.video_type)+Z("_vce",this.ec)+Z("c",Math.round(za(this.Yd)/
600)/100)+"&W=0&R="+(c==="s2"?"1":"0")+"&I="+(c!=="s2"?"1":"0")+"&E="+this.fc+"&j="+(this.Xa/1E3+15)+Gc(this)+"&tz="+(new Date).getTimezoneOffset()+(zb(this.G)?"&l=1":"")+"&_";this.Na===g&&t(f,function(a){window.top.postMessage("cbqpush::"+a.join("::"),"*")});this.fb(a)}};function Z(a,b){return b!==e&&b!==""?"&"+a+"="+b:""}o.cb=function(){this.G.update("_cb_cp",this.Ea,60,j,",")};function Gc(a){var b=a.G.F("_cb_cp");a.G.remove("_cb_cp");return b?"&D="+b:""}
function Hc(a){return a.k.subdomain?a.k.subdomain:oa(q.location.hostname)}function Ac(a){var b=a.ua.videopath;if(b)return b;if(a.k.videoPathHash){if(a=Ec(a))return ja(a)}else return a.J.getVideoPath();return""}function Ec(a){return a.ua.title||a.J.getTitle()}function Dc(a){return a.ua.thumbnailpath||a.J.getThumbnailPath()}
function Fc(a){var b=a.k,c=a.J,d=q.location,f=c.getUid&&c.getUid()||b.uid,i=b.videodomain||c.getHost&&c.getHost()||b.domain,i=encodeURIComponent("video@"+i),n="",r=a.eb?"&b="+a.eb:"",p,C=a.k.path;p=a.k.useSubDomains!==j&&C&&C.substr(0,1)==="/"?Hc(a)+C:C;var C=c.getSections&&c.getSections(),M=c.getAuthors&&c.getAuthors(),P=b.sections?"&g0="+encodeURIComponent(b.sections):"",S=b.authors?"&g1="+encodeURIComponent(b.authors):"",C=C===e||b.videoPageGroups?P:"&g0="+encodeURIComponent(C.join(",")),M=M===
e||b.videoPageGroups?S:"&g1="+encodeURIComponent(M.join(",")),S="",P=Ac(a);if(a.ub===e)a.ub=P;else if(P!=a.ub)S=Z("D",a.Ea),a.Ea=ja(Ib(a)),a.ub=P,a.kb=0,a.jb=0,a.fc=0,a.ec=0,a.Zb=g;if(a.Zb||S){if(a.Na===j||a.Na===g&&a.Fc===g)a.Zb=j;n=(Lb(a)?"&v=":"&r=")+Mb(a)}a.fc+=a.kb;a.kb=0;a.ec+=a.jb;a.jb=0;Cc(a);var ha=P="",ca="",N="",E="",sa="",ka="",la="";if(!a.Na===g||a.Xb===g)P="&_vi="+Nb(a),ha="&_vp="+encodeURIComponent(p),ca="&_vh="+wa(Hc(a)),N="&_vdd="+encodeURIComponent(b.domain),a.Xb===g?(E=b.u,sa=b.t,
ka=Na(b.v),la=Na(b.r)):(E=H("u"),sa=H("t"),ka=Na(H("v")),la=Na(H("r")));p="";p=ta(ka)?"&_pv="+ka:ta(la)?"&_pr="+la:"&_pr=NA";ka="&_pu=";la="&_pt=";ka+=E?E:"NA";la+=sa?sa:"NA";E=!b.noCookies&&a.G.isSupported();sa=c.getStrategyName?c.getStrategyName():"";return(d.protocol||"http:")+"//"+b.pingServer+"/ping?h="+i+"&g="+f+"&p="+wa(Ac(a))+"&i="+wa(Ec(a))+C+M+"&u="+a.Ta+"&t="+a.Ea+"&x=0&y=0&V=78"+Z("VS",sa)+(E?"&n="+a.Pb:"&nc=1")+r+n+S+Z("_vd",c.getTotalDuration())+P+ha+ca+ka+la+p+N}
o.Gb=function(){var a=Bc(this);if(this.Wb!=a)this.Wb=a,Cc(this),this.ka()};function Cc(a){var b=a.Xa;a.Xa=(a.J.getState()==="s2"||Ic(a))===g?5E3:a.J.getState()===O?wc:15E3;if(b!=a.Xa)b=a.Xa,clearInterval(a.Pa),a.Pa=setInterval(v(a.ka,a),b)}function Bc(a){return a.J.getState()+a.J.getAdPosition()}function Ic(a){return a.J.getAdPosition()!==""&&a.J.getAdPosition()!==e&&a.J.getViewAdPlayTime!==-1&&a.J.getViewAdPlayTime!==e}
o.ad=function(){if((this.J.getState()==="s2"||Ic(this))===g)this.kb+=1,this.J.getContentType()===L&&(this.jb+=1)};o.Ud=function(){window.parent.postMessage("cbdata?","*")};
o.pd=function(a){if(a.source===window.parent&&(a=a.data,ta(a)&&a.indexOf("domain=")===0)){this.Xb=g;var b={domain:g,uid:g,path:g,title:g,referrer:g,internal:g,subdomain:g,token:g,u:g,t:g,v:g,r:g},c=this;t(a.split("&"),function(a){var a=a.split("="),f=a[0],a=a[1];b[f]&&(c.k[f]=decodeURIComponent(a))});qa(window,"message",this.qb);clearInterval(this.ib);this.ib=e;this.Fc=g;this.ka()}};o.setProperty=function(a,b){var c=j,d=this;t(yc,function(f){if(a.toLowerCase()==f)return d.ua[f]=b,c=g,j});return c};
o.terminate=function(){clearInterval(this.pc);clearInterval(this.ib);clearInterval(this.Ia);qa(window,"message",this.qb);vc.ma.terminate.call(this)};o.xa=function(){vc.ma.xa.call(this);this.Mc=this.a=this.qb=h};function $(a){this.a=a;this.D=g;this.B=j;this.q=u();this.Ia=this.za=this.Da=e;this.Oc=q._sf_async_config.ytApikey;this.Wa=e;Jc(this,Kc(this));this.ia()}o=$.prototype;o.ia=function(){this.Ia=setInterval(s(this.Gb,this),100);var a=this.a.getPlayerState();(a===1||a===2||a===0)&&this.ga()};o.Gb=function(){if(this.a.getPlayerState()===1)clearInterval(this.Ia),this.Ia=e,this.ga()};o.la=function(){this.D=g};o.ga=function(){if(!this.B)this.B=g};
function Kc(a){var b;return(b=(a=a.a.getVideoUrl())&&a.match(/[?&]v=([^&]+)/),a=b)&&a[1]}function Jc(a,b){var c="https://www.googleapis.com/youtube/v3/videos?part=snippet&id="+b+"&key="+a.Oc,d=v(function(){this.Wa={id:b,title:""}},a);if(a.Oc){var f=v(function(a){if(b==Kc(this))a?a.error?d():this.Wa={id:b,title:a&&a.items&&a.items[0]&&a.items[0].snippet&&a.items[0].snippet.title||""}:d()},a);Aa(c,f)}else d()}o.P=function(){return this.D&&!!this.Wa};
o.N=function(){return this.Wa&&this.Wa.id===Kc(this)?this.Wa.title:""};o.O=function(){return Kc(this)||this.a.getVideoUrl()};o.X=function(){return L};o.Q=m("");o.da=function(){var a=this.a.getDuration();return ra(a)?a*1E3:a};o.M=function(){if(!this.B)return O;var a=this.a.getPlayerState();return a===0?"s4":a===2?"s3":"s2"};o.Y=function(){var a=this.a.getCurrentTime();return x(a)};o.U=m(-1);o.ca=function(){return"http://img.youtube.com/vi/"+Kc(this)+"/default.jpg"};o.$=k();o.T=k();
o.ea=function(){return isNaN(this.q)?0:za(this.q)};o.aa=l("Da");o.S=l("za");o.ba=m("YT");$.prototype.getStrategyName=$.prototype.ba;$.prototype.isReady=$.prototype.P;$.prototype.getTitle=$.prototype.N;$.prototype.getVideoPath=$.prototype.O;$.prototype.getContentType=$.prototype.X;$.prototype.getAdPosition=$.prototype.Q;$.prototype.getTotalDuration=$.prototype.da;$.prototype.getState=$.prototype.M;$.prototype.getCurrentPlayTime=$.prototype.Y;$.prototype.getBitrate=$.prototype.U;
$.prototype.getThumbnailPath=$.prototype.ca;$.prototype.getPlayerType=$.prototype.$;$.prototype.getAutoplayType=$.prototype.T;$.prototype.getViewStartTime=$.prototype.ea;$.prototype.getSections=$.prototype.aa;$.prototype.getAuthors=$.prototype.S;$.verify=function(a){return ua(a.getDuration)&&ua(a.getVideoUrl)&&ua(a.getVideoEmbedCode)};function Lc(){q._cbv_strategies||(q._cbv_strategies=[]);q._cbv_strategies.push(X);q._cbv_strategies.push(U);q._cbv_strategies.push(T);q._cbv_strategies.push($);q._cbv_strategies.push(V);q._cbv_strategies.push(R);q._cbv_strategies.push(Q);q._cbv_strategies.push(W);q._cbv_strategies.push(Y);this.gc=[];this.ua=[];this.k=q._sf_async_config||{};tb("_cbv",v(this.qd,this));if(this.k[xc]!==j)this.tc(),this.Ca=La(v(this.tc,this),5E3),setTimeout(v(function(){y(this.Ca)},this),3E4)}
Lc.prototype.qd=function(a){if(aa(a)=="array"&&typeof a[0]=="string"){var b=a[0];if(b==="autoDetectYouTubeIframes"){Mc();return}else if(b==="removePlayer"){Nc(this,a[1]);return}else if(b==="setProps"){Oc(a[1])||this.ua.push(a[1]);return}}Pc(this,a)};function Pc(a,b){var c=j,d=q._cbv_strategies;w(window.jwplayer)&&(b=ua(b)?b():b);t(d,function(a){if(a.verify(b)===g)return c=a,j});c===j||Qc(a,b,c)}
function Nc(a,b){var c=a.gc,d=q.pSUPERFLY_video,f=xa(c,function(a){return b===a});f!==-1&&c.splice(f,1);f=xa(d,function(a){return a.a===b});f!==-1&&d.splice(f,1)[0].xa()}function Oc(a){if(!w(a))return j;var b=a.player,c=ya(function(a){return a.a===b});return!w(c)?j:Rc(c,a)}function Rc(a,b){var c=j;t(b,function(b,f){if(f!=="player"&&(c=a.setProperty(f,b),!c))return c});return c}
function Qc(a,b,c){var d=j;t(a.gc,function(a){if(b===a)return d=g,j});if(!d){c=new vc(b,c);q.pSUPERFLY_video.push(c);for(var f=a.ua.length-1;f>-1;f--)Rc(c,a.ua[f])&&a.ua.splice(f,1);Jb(c);a.gc.push(b)}}
Lc.prototype.tc=function(){if(ua(window.jwplayer)&&w(window.jwplayer())){y(this.Ca);for(var a=0,b=window.jwplayer(a);w(b.id);)window._cbv.push(b),b=window.jwplayer(++a)}else window.flowplayer?(y(this.Ca),window._cbv.push(window.flowplayer)):window.brightcove&&window.experienceJSON?(y(this.Ca),window._cbv.push(window.brightcove)):window.videojs?(y(this.Ca),a=window.videojs.plugin,ua(a)&&a("chartbeat",function(a){this.cb_configs=a;window._cbv.push(this)})):window.kWidget?(y(this.Ca),window.kWidget.addReadyCallback(function(a){window._cbv.push(document.getElementById(a))})):
window.$pdk?(y(this.Ca),window._cbv.push(window.$pdk)):t(document.getElementsByTagName("video"),function(a){window._cbv.push(a)})};
function Mc(){function a(){function a(b){q._cbv.push(b.target)}var b=q.YT.Player;t(document.getElementsByTagName("iframe"),function(f){var i=f.src,n=i&&i.indexOf("www.youtube.com/embed/");i&&n>=0&&n<9&&new b(f,{events:{onReady:a}})})}if(q.YT&&q.YT.Player)a();else{var b=q.onYouTubeIframeAPIReady;q.onYouTubeIframeAPIReady=function(){if(b){try{b.apply(q,arguments)}catch(c){}a()}}}};if(window.location==window.parent.location&&!q.pSUPERFLY){var Sc=new mc,Tc={};q.pSUPERFLY=Tc;var Uc=!!ec;Tc.virtualPage=function(a,b){if(!db){var c=q._sf_async_config;c.virtualReferrer=q.location.protocol+"//"+c.domain+c.path;c.path=Cb(a);b&&(c.title=b);Sc.lb();Uc&&ec.evps();Sc.Kc();Uc&&ec.svps()}};Tc.activity=v(Sc.Uc,Sc);Jb(Sc);var Vc=G.Z(g);if(Vc)if(Vc.getItem("_cb_ip")){var Wc=q.location;(!/^(.+[.])?chartbeat\.com$/.test(Wc.hostname)?0:/^\/publishing\/(overlay|hud|mab)\//.test(Wc.pathname))||kc()}else pa(q,
"message",lc)}q.pSUPERFLY_video||(q.pSUPERFLY_video=[]);new Lc;})();
